# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e34afda137bcfbfbfbf0e1cc282c99ad3e69bf6c075de4e82d3a5d698871f6c57c3c4edd719d5d2d14f82679f8eb0aad2a67bfc57dee5e5434ba26a269cc38e4

test:
  secret_key_base: 7f14af5d24bceff5f7c2de879cd342a26e895a9cda98850e17567a7243e015cc5ed2780eb6e2f62c5974e642b8f2f823b1807d886878a0854069664ffb4c2002

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
